export const GlobalTypes = {
  REQUEST_HEARTBEAT: 'REQUEST_HEARTBEAT',
  REQUEST_DATA: 'REQUEST_DATA',
  METRIC_GET: 'METRIC_GET',
  METRIC_ADD: 'METRIC_ADD',
  WEATHER_DATA: 'WEATHER_DATA',
  API_ERROR: 'API_ERROR',
};
